foreground   #ff6996
background   #20000f
cursor       #ff6996

color0   #20000f
color1   #ff595f
color2   #8eff69
color3   #ffdd59
color4   #f2477a
color5   #760023
color6   #ff0055
color7   #ffedf2
color8   #a5979b
color9   #ffffff
color10   #b0ff96
color11   #ffe996
color12   #ff7fa5
color13   #ff96b5
color14   #ffbbcf
color15   #fff7f9
