# BEGIN_KITTY_FONTS
font_family      family="Rixlovefool Cyrillic Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
include colors-kitty.conf
cursor_trail 3
enabled_layouts tall,fat,grid,horizontal,vertical
map alt+s next_layout
map alt+h neighboring_window left
map alt+t neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down
